############################################################
#                       Discord-MCPE                       #
#                        By: Niekert                       #
#                         Support:                         #
#   https://github.com/NiekertDev/Discord-MCPE/issues/new  #
#   Credit to Thunder33345 for helping with small things   #
#         Credit to TheRoyalBlock for config design        #
#               Main options section (below)               #
############################################################

webhook_url: "https://discordapp.com/api/webhooks/548281888671006730/OOGlg7sgYQ95D53wm0eDKn5DbtKfiztvFOPRoxHtRYfU23ShL-UilOBtkaHVx7EzhvFM"
# Your discord webhook url.

chat_url: "https://discordapp.com/channels/548198157885112321/548198326223372308" 
# Webhook url for the /discord command and when somebody chats. Set to 0 to use default.

username: "DISCORD-MCPE" 
# The username the plugin uses in discord.

chat_username: "logs-in-game" 
# The username of the plugin for /discord and when someone chats. Set to 0 to use default.

chat_format: "[{player}] {message}"
# Format in discord that the plugin uses when sending a message. {rank}, {player}, and {message} can be used.

############################################################
#                     Messages on Event                    #
#   These messages are triggered on an event such as when  #
#   the server starts or stops, or when a player joins or  #
#             leaves. Also when a player dies.             #
#        Tip: Set any of these to 0 to disable them        #
############################################################

start_message: "Server started" 
# Message sent when server starts.

shutdown_message: "Server has been shutdown by itself or a issue occured." 
# Message sent when server stops.

join_message: "Player:{player}Rank:{rank} has joined the game" 
# Message sent when player joins. {player} and {rank} can be used.

quit_message: "Player:{player}:{rank} has left the game"
# Message sent when player leaves. {player} and {rank} can be used.

death_message: "User {player} Just died because he couldn't fight or swim" 
# Message sent when player get killed. {player} and {rank} can be used.

############################################################
#                       Other Options                      #
#  It is not recommended that you change these, especially #
#         if you do not understand what they mean.         #
#      Tip: Set any of these to false to disable them      #
#       Tip: Set any of these to true to enable them       #
############################################################

command: true
# Enable/disable "/discord"

chat_prefix: "!!" 
# Prefix for chat. See README.md for more info.

chat: false
# Send everything to Discord. Recommended to keep this disabled, but it can be used.

pureperms: false
# Support for PurePerms rank names. PurePerms ranks use the prefix {rank}.
# If not enabled, {rank} tags will show as "{rank}".

debug: falsE
# Show error messages. Set to 1 to enable.

#####################################################
#     UNDER NO CIRCUMSTANCES SHOULD YOU EDIT THE    #
#                  FOLLOWING LINE!                  #
Version: "1.0.2"
#     Thank you for not editing the line above!     #
#####################################################
